# Generated by Django 5.2.7 on 2025-10-26 18:44

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('year_founded', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Racquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_year', models.PositiveSmallIntegerField()),
                ('head_size_in2', models.PositiveSmallIntegerField()),
                ('length_in', models.FloatField()),
                ('unstrung_weight_g', models.PositiveSmallIntegerField()),
                ('strung_weight_g', models.PositiveSmallIntegerField()),
                ('swing_weight', models.PositiveSmallIntegerField()),
                ('twist_weight', models.PositiveSmallIntegerField()),
                ('balance_mm', models.PositiveSmallIntegerField()),
                ('mains', models.PositiveSmallIntegerField()),
                ('crosses', models.PositiveSmallIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RacquetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(upload_to=catalog.models.racquet_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('racquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.racquet')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
