# Generated by Django 5.2.6 on 2025-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racquet',
            name='twist_weight',
            field=models.FloatField(),
        ),
    ]
