# Generated by Django 5.2.6 on 2025-11-30 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_racquet_twist_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RacquetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('racquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by', to='catalog.racquet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racquet_collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'racquet')},
            },
        ),
    ]
